version: 2
jobs:
   docker-tests:
     docker:
       - image: circleci/golang:1.7
     steps:
       - checkout
       - run: ./setup.sh
       - run: cat /etc/resolv.conf
       - run: ./dig-docker-dns.sh

   machine-tests:
     machine:
       enabled: true
     steps:
       - checkout
       - run: ./setup.sh
       - run: cat /etc/resolv.conf
       - run: ./dig-docker-dns.sh

workflows:
  version: 2
  all-tests:
    jobs:
      - docker-tests
      - machine-tests
